[package]
name = "eew-renderer-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
base65536 = "1.0.1"
bytes = "1.6.0"
prost = "0.12.6"
serde = "1.0.210"
serde_json = "1.0.128"

[build-dependencies]
prost-build = "0.12.6"
