syntax = "proto3";

package net.eewbot;

import "models/code_array.proto";
import "models/epicenter.proto";

message QuakePrefectureData {
    uint64 time = 1;
    optional net.eewbot.models.Epicenter epicenter = 2;

    net.eewbot.models.CodeArray one = 3;
    net.eewbot.models.CodeArray two = 4;
    net.eewbot.models.CodeArray three = 5;
    net.eewbot.models.CodeArray four = 6;
    net.eewbot.models.CodeArray five_minus = 7;
    net.eewbot.models.CodeArray five_plus = 8;
    net.eewbot.models.CodeArray six_minus = 9;
    net.eewbot.models.CodeArray six_plus = 10;
    net.eewbot.models.CodeArray seven = 11;
}
